version: '3'
services:
  dynamodb:
    image: cnadiminti/dynamodb-local
    volumes:
      - ./.data/dynamodb:/dynamodb_local_db
    ports:
      - 8000:8000
  server:
    image: node:10-alpine
    working_dir: /app
    command: npm test
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=eu-west-3
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DYNAMODB_TABLE_NAME=TestDomains
    volumes: 
      - ./:/app
    ports: 
      - 3000:3000
    depends_on:
      - dynamodb
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment: 
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=eu-west-3
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on: 
      - dynamodb
    ports:
      - 8001:8001